### ISSUE TITLE
It's not working on chrome

### ISSUE THREAD

**Issue by Phe0nix** [mdn/voice-change-o-matic#18]
Hi, 
I tried to play it on chrome but click the mute button and nothing's happening. 
Can you please write some instruction how it will work?

**Comment by chrisdavidmills** [comment]
@Phe0nix ah yes, this was no longer working because of autoplay policy (already active in Chrome, soon to be active in Firefox). Because automatically playing sound on web pages is really annoying, you've now got to initiate it via a user geture such as a click event.

I don't have the time to make this look beautiful, so for now I've just put the app code inside a function, which runs when you click anywhere on the document body.
